<?php

namespace App\Controller\Admin;

use App\Entity\Text;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class TextCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Text::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        $crud->showEntityActionsInlined();

        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        yield TextField::new('key')->setDisabled($pageName !== Action::NEW);
        yield TextField::new('location');
        yield TextEditorField::new('content');
    }
}
